[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, s-max-age=43200"

[[headers]]
  for = "/dist/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=43200"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
